### ISSUE TITLE
Working Good but having a major problem

### ISSUE THREAD

**Issue by stingyman12** [Cryptonian007/Astra#1]
Everything went good for me
But after adding 9-10 accounts it's auto exiting Any solution for this>??

**Comment by Cryptonian007** [comment]
What do mean by auto exit bud? Can you please be clear about it?

**Comment by Cryptonian007** [comment]
Okay yeah, the accounts get limited instantly after adding only few members. I'm looking into it.
This script is currently unstable.

**Comment by stingyman12** [comment]
> Okay yeah, the accounts get limited instantly after adding only few members. I'm looking into it.
> This script is currently unstable.

Exactly!

**Comment by kenxs33** [comment]
Can the add method be changed to user id?

**Comment by Cryptonian007** [comment]
It adds by user id

**Comment by Cryptonian007** [comment]
@stingyman12 commited just now. Try

**Comment by stingyman12** [comment]
> @stingyman12 commited just now. Try

is the update thing working in manager.py? it force closes

**Comment by Cryptonian007** [comment]
@stingyman12 send screenshot

**Comment by Cryptonian007** [comment]
@stingyman12 lol that doesn't works 😂 . I have fixed that

**Comment by stingyman12** [comment]
[i] User: Adam Olk -- Sleep 60 second(s)
[!] User: Adam Olk -- Peer Flood Error.
[-] User: Adam Olk -- User Privacy Restricted Error

[i] Adding session ended
[i] Session stored in status.dat

 Press enter to exit...
 
 Any solution for this?

**Comment by Cryptonian007** [comment]
It doesn't add endlessly. It tries to add 60 members
send screenshot so that I can be more clear about it

**Comment by stingyman12** [comment]
Can we add members to the 
channel too?

**Comment by Cryptonian007** [comment]
nope buddy, only groups

**Comment by stingyman12** [comment]
> It doesn't add endlessly. It tries to add 60 members
> send screenshot so that I can be more clear about it

![bandicam 2021-05-24 12-59-11-541](https://user-images.githubusercontent.com/81790841/119312419-f6174f00-bc8f-11eb-8302-efea15768a63.jpg)

**Comment by stingyman12** [comment]
adding few members and exiting

**Comment by Cryptonian007** [comment]
@stingyman12 see bud, you have chosen to add active members. So it skips members that are not active
u can also set the sleep time as 0s...ur wish actually, if u wanna add fast ; but account may get limited soon

**Comment by stingyman12** [comment]
Its a group of 580 members and almost everyone are having last seen recently but the script is exiting after a few accounts
Thanks for your quick responses !!!!
Awesome script by the way!

**Comment by Cryptonian007** [comment]
Lol then try giving "n" there
Anyway, thanks for ur compliment 😄

**Comment by stingyman12** [comment]
> Lol then try giving "n" there
> Anyway, thanks for ur compliment 😄

n??

**Comment by Cryptonian007** [comment]
`Do you wanna add active members? [y/n]: n`

**Comment by stingyman12** [comment]
Working good now 
Thanks!

> `Do you wanna add active members? [y/n]: n`
