### ISSUE TITLE
Astra 1.2 version not work

### ISSUE THREAD

**Issue by polseyha** [Cryptonian007/Astra#11]
[*] -- Adding members from 1 account(s) --
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Astra/add.py", line 174, in <module>
    print(f'{plus}{grey} User: {cy}{acc_name}{lg} -- {cy}Starting session... ')
NameError: name 'acc_name' is not defined

**Comment by Cryptonian007** [comment]
It has been fixed. Update again.
