### ISSUE TITLE
ResolveUsernameRequest

### ISSUE THREAD

**Issue by Whik06** [Cryptonian007/Astra#12]
Hello, 

Firstly thank you for the script it worked perfectly!

I've got the issue today trying to reinstall the scraper on a reset computer with the following problem, could you help me please?

~] Enter delay time per request[0 for None]: 10
[*] -- Adding members from 1 account(s) --
[+] User: +84398016047 -- Starting session...
[+] User: Mikayla -- Joined group to scrape
[!] User: Mikayla -- Failed to join group
[!] Nobody is using this username, or the username is unacceptable. If the latter, it must match r"[a-zA-Z][\w\d]{3,30}[a-zA-Z\d]" (caused by ResolveUsernameRequest)

**Comment by Whik06** [comment]
Issue solved I added too many people. However the function to add active members does not appear anymore, is that normal?

**Comment by Cryptonian007** [comment]
Yes it's normal. I've removed it. I'll include it in the next update.
