### ISSUE TITLE
Please I need this file

### ISSUE THREAD

**Issue by Mufasa247** [Cryptonian007/Astra#14]
I can't see where to download this termux script. Please help me with it. Thank you and God bless you

**Comment by owenscan** [comment]
If you're on Android, check playstore

**Comment by owenscan** [comment]
Just use repl.it 
It's better than way

**Comment by Cryptonian007** [comment]
If you want to use it in termux, do the following:

Install git

`apt-get install git`

Clone the repo

`git clone https://github.com/Cryptonian007/Astra.git`

**Comment by Mufasa247** [comment]
Thank you sir for providing me with the git clone of your script I am so
happy. May God bless you sir.

Please I have another request Sir, kindly assist and help me with the
commands needed to perform a scraping and adding of members using this your
script on termux.

I have already downloaded termux sir, I'm just awaiting your commands so I
can add members to my chemistry group.

Thanks once again.
