### ISSUE TITLE
ACCOUNTS GETTING BANNED AND USERS GETTING VANISHED!!

### ISSUE THREAD

**Issue by pavan061994** [Cryptonian007/Astra#2]
ACCOUNTS GETTING BANNED AND USERS GETTING VANISHED AFTER USING THIS SCRIPT... OLD ONE GENISYS IS FAR BETTER THAN ASTRA.

Also, can you pls work on integrating 2FA in Genisys as well?

**Comment by Cryptonian007** [comment]
Hi,
U can try inceasing sleep time in Astra.
Moreover, I'll work on 2FA in Genisys

**Comment by Cryptonian007** [comment]
Btw, i have committed yesterday, did u try the new one? I've tested yesterday and it worked like a charm
Even it could add at sleep 0. But received flood wait soon cuz I used a VoIP number

**Comment by pavan061994** [comment]
I tried bro.. but now my 80 telegram accounts got banned and members added by them are also left ... 1300 Members got minus!

**Comment by Cryptonian007** [comment]
Can u provide me some more details?
1) What was the delay time that u enter?
2) Was the error `Banned from writing in groups` ?

**Comment by pavan061994** [comment]
Delay was 0 ...

And yes I got this error in 2nd Re-Run...

And My group Subs were at 3300 in the morning and now they are at 1900 and going down.

The telegram accounts that I used to add members got Deleted Account and this issues started coming in.

**Comment by Cryptonian007** [comment]
3. How many members did u add?
4. Did u entered this?
`Do you wanna add active users? [y/n]: y`
End of questions

**Comment by pavan061994** [comment]
3: I used 50 - 100 accounts ... got added 400 and then Boom -- Accounts started banning and Members getting vanished... now at 1800!

4: Yes I used Y option.

**Comment by Cryptonian007** [comment]
Ur answers met my expectations
Here's my answer:
Firstly, all members didn't get added cuz it skips users if they are inactive.
Secondly, since they are active members, when added they have a option to report and leave
Thirdly, there's no such thing as "vanishing members". They leave by themselves. There's no magician working out there
Fourthly, when your accounts get too many spam reports, telegram limits them permanently from msging in groups, or ban them either. 
Due to that, you have faced the error `Banned From Writing In Groups`

Hope this helps

**Comment by pavan061994** [comment]
Okay... So any idea how can I go steady n slow. ? Wanted to increase genuinely my group count.

**Comment by Cryptonian007** [comment]
Hmm, I have some suggestions. Try adding the delay time and adding inactive members too. Not much I can do about these, afterall spam reports are reports. I can't stop them from teaching telegram moderators

**Comment by Cryptonian007** [comment]
Or try Genisys

**Comment by pavan061994** [comment]
Genisys is what i feel better ..safer... Just 2FA is problem .. if that is integrated then it will be great help.

Thanks in advance :D

**Comment by Cryptonian007** [comment]
Okay. I'll work on 2FA whenever I'll be free next time

**Comment by pavan061994** [comment]
Okay bro.. Thank you.
