### ISSUE TITLE
ERROR : Invalid iteral for int() 

### ISSUE THREAD

**Issue by DeLaCroix-** [Cryptonian007/Astra#3]
I'm scraping members succesfully and got a 'members.csv'.
However, when I execute one of the adders (like addbyid.py or usradder.py) got the first error.

Terminal : `python .\usradder.py  `

Response : 
```
Traceback (most recent call last):
  File "C:\Users\astra\usradder.py", line 39, in <module>
    api_id = int(sys.argv[1])
IndexError: list index out of range
```

Then, I execute usradder with the .csv. 
Terminal : `python .\usradder.py .\members\members.csv`

But I got another error.
Response:
```
Traceback (most recent call last):
  File "C:\Users\astra\usradder.py", line 39, in <module>
    api_id = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: '.\\members\\members.csv'
```

Any idea?

Thank you in advance!

**Comment by Cryptonian007** [comment]
Hi,
You must raise this in [Genisys repository](https://github.com/Cryptonian007/Genisys.git) and not here. Moreover, for adding, you must run `tsadder.py` (After you have scraped members)
