### ISSUE TITLE
 f = open('vars.txt', 'rb')

### ISSUE THREAD

**Issue by taswarshah** [Cryptonian007/Astra#5]
Traceback (most recent call last):
  File "C:\Users\Taswar Hussain\Desktop\Astra-main\add.py", line 69, in <module>
    f = open('vars.txt', 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'vars.txt'

**Comment by taswarshah** [comment]
Reminder

**Comment by taswarshah** [comment]
**Reminder….**

**Comment by Cryptonian007** [comment]
Make sure you have added your accounts using `manager.py`. Because account list is logged in `vars.txt`

**Comment by taswarshah** [comment]
Thanks
